### ISSUE TITLE
arXivはGateway経由でアクセスできない

### ISSUE THREAD

**Issue by yoshi74ls181** [Tagussan/GoogleScholarOnUTokyoGateway#1]
arXiv上にしかない文書は、arXivへのリンクがGatewayを経由するように書き換えられてしまいます。
東大のGatewayはarXivへのアクセスをブロックしているため、そのリンクをクリックすると

> Access to the Web site is blocked by your administrator. Please notify your system administrator. Made http request for GET /abs/* HTTP/1.1 to arxiv.org:80

と表示され、アクセスできません。
arXivへのリンクについては書き換えを行わないようにしていただけると有り難いです。

**Comment by yoshi74ls181** [comment]
上は誤操作です、申し訳ございません。

**Comment by Tagussan** [comment]
報告ありがとうございました。コミット 20cccff にて対応致しました。

**Comment by yoshi74ls181** [comment]
迅速なご対応ありがとうございます。
引き続き便利に使用させていただきます。
